services:
  # Backend API service
  - type: web
    name: current-media-pms-api
    runtime: node
    buildCommand: cd server && npm install && npm run build
    startCommand: cd server && npm start
    plan: starter
    numInstances: 1
    region: ohio
    domains:
      - api.currentmedia.ca
    envVars:
      # Server Config
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      # Admin Config
      - key: ADMIN_EMAIL
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      # Email Config
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        sync: false
      - key: SMTP_SECURE
        sync: false
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: SMTP_FROM
        sync: false
      - key: JAKE_EMAIL
        sync: false
      # JWT Config
      - key: JWT_SECRET
        sync: false
      # ClickUp Config
      - key: CLICKUP_API_KEY
        sync: false
      - key: CLICKUP_WORKSPACE_ID
        sync: false
      - key: CLICKUP_CLIENT_ID
        sync: false
      - key: CLICKUP_CLIENT_SECRET
        sync: false
      - key: CLICKUP_REDIRECT_URL
        sync: false
      # Storage Config
      - key: STORAGE_PATH
        value: /data
    disk:
      name: data
      mountPath: /data
      sizeGB: 1

  # Frontend static site
  - type: web
    name: current-media-pms-client
    runtime: static
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: ./client/dist
    plan: starter
    domains:
      - currentmedia.ca
      - www.currentmedia.ca
    envVars:
      - key: VITE_API_URL
        value: /api
      - key: VITE_APP_URL
        value: /pms
    routes:
      - type: rewrite
        source: /pms/*
        destination: /index.html
      - type: rewrite
        source: /api/*
        destination: https://current-media-pms-api.onrender.com/api/:splat
