services:
  - type: web
    name: current-media-project-management
    env: node
    buildCommand: |
      cd client && npm install && npm run build
      cd ../server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: current-media-db
          property: connectionString
      - key: CLICKUP_API_KEY
        sync: false
      - key: JWT_SECRET
        generateValue: true

databases:
  - name: current-media-db
    plan: standard
    ipAllowList: []
