services:
  # Frontend static site
  - type: web
    name: current-media-pms-client
    runtime: static
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: ./client/dist
    routes:
      - type: rewrite
        source: /pms/*
        destination: /index.html
      - type: rewrite
        source: /api/*
        destination: https://current-media-pms-api.onrender.com/api/:splat
